{{- $ingress := lookup "config.openshift.io/v1" "Ingress" "cluster" "openshift-ingress-operator" -}}
apiVersion: apps.3scale.net/v1alpha1
kind: APIManager
metadata:
  name: apimanager
  namespace: '{{ .Values.namespace }}'
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  wildcardDomain: '{{ $ingress.spec.domain }}'
  resourceRequirementsEnabled: false
  tenantName: maas
  system:
    fileStorage:
      simpleStorageService:
        configurationSecretRef:
          name: 3scale-s3-credentials
  apicast:
    stagingSpec:
      customPolicies:
        - name: llm-metrics
          version: "0.1"
          secretRef:
            name: llm-metrics
    productionSpec:
      customPolicies:
        - name: llm-metrics
          version: "0.1"
          secretRef:
            name: llm-metrics
