apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: guardrails-hf-hap

helmCharts:
- name: guardrails-hf-detector-kserve
  releaseName: granite-guardian
  version: 0.1.3
  repo: https://redhat-ai-services.github.io/helm-charts/
  valuesFile: values.yaml
