apiVersion: batch/v1
kind: Job
metadata:
  name: 3scale-dev-portal-deploy
  namespace: '{{ .Values.namespace | default "maas-3scale" }}'
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "6"
spec:
  template:
    spec:
      restartPolicy: OnFailure
      initContainers:
      - name: clone-and-copy
        image: registry.redhat.io/openshift4/ose-tools-rhel9:latest
        command: ["/bin/sh"]
        args:
        - "-c"
        - |
          /usr/bin/git clone https://github.com/rh-aiservices-bu/models-aas.git /tmp/models-aas &&
          cp -r /tmp/models-aas/deployment/3scale/portal/. /cms

          export THREESCALE_ACCESS_TOKEN=$(oc get secret system-seed -o json -n {{ .Values.namespace | default "maas-3scale" }} | /usr/bin/jq -r '.data.ADMIN_ACCESS_TOKEN' | base64 -d)
          export THREESCALE_ADMIN_HOST=$(oc get route -n {{ .Values.namespace | default "maas-3scale" }} | grep maas-admin | awk '{print $2}')

          mkdir -p /tmp/3scale
          echo ${THREESCALE_ACCESS_TOKEN} > /cms/access_token
          echo ${THREESCALE_ADMIN_HOST} > /cms/admin_host

          ls -l /cms

        volumeMounts:
        - name: cms-volume
          mountPath: /cms
      containers:
      - name: cms-upload
        image: ghcr.io/fwmotion/3scale-cms:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          export ACCESS_TOKEN=$(cat /cms/access_token)
          rm /cms/access_token
          export ADMIN_HOST=$(cat /cms/admin_host)
          rm /cms/admin_host

          alias cms="java -Djava.util.logging.manager=org.jboss.logmanager.LogManager -jar /home/jboss/quarkus-run.jar"

          #echo "Clean up developer portal content... This may take a moment."
          #cms -k --access-token="${ACCESS_TOKEN}" "${ACCESS_TOKEN}" "https://${ADMIN_HOST}" delete --yes-i-really-want-to-delete-the-entire-developer-portal

          echo "Updating developer portal content... This may take a moment."
          cms -k --directory=/cms --access-token="${ACCESS_TOKEN}" "${ACCESS_TOKEN}" "https://${ADMIN_HOST}" upload -u --delete-missing --layout=/l_main_layout.html.liquid
        volumeMounts:
        - name: cms-volume
          mountPath: /cms
      volumes:
      - name: cms-volume
        emptyDir: {}
