apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: maas-3scale-system-seed
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    rhoai-example: maas-3scale
    rhoai-example-component: shared-secrets
spec:
  namespaceSelectors:
    - matchLabels:
        rhoai-example-component: 3scale
  refreshTime: 0s
  externalSecretName: system-seed
  externalSecretMetadata:
    labels:
      rhoai-example: maas-3scale
      rhoai-example-component: shared-secrets
  externalSecretSpec:
    refreshInterval: 0s
    dataFrom:
      - sourceRef:
          generatorRef:
            apiVersion: generators.external-secrets.io/v1alpha1
            kind: ClusterGenerator
            name: maas-3scale-password-generator
        rewrite:
          - regexp:
              source: password
              target: MASTER_PASSWORD
      - sourceRef:
          generatorRef:
            apiVersion: generators.external-secrets.io/v1alpha1
            kind: ClusterGenerator
            name: maas-3scale-secret-key-generator
        rewrite:
          - regexp:
              source: password
              target: MASTER_ACCESS_TOKEN
      - sourceRef:
          generatorRef:
            apiVersion: generators.external-secrets.io/v1alpha1
            kind: ClusterGenerator
            name: maas-3scale-password-generator
        rewrite:
          - regexp:
              source: password
              target: ADMIN_PASSWORD
      - sourceRef:
          generatorRef:
            apiVersion: generators.external-secrets.io/v1alpha1
            kind: ClusterGenerator
            name: maas-3scale-secret-key-generator
        rewrite:
          - regexp:
              source: password
              target: ADMIN_ACCESS_TOKEN
    target:
      name: system-seed
      immutable: true
      template:
        engineVersion: v2
        metadata:
          labels:
            rhoai-example: maas-3scale
            rhoai-example-component: shared-secrets
        data:
          MASTER_USER: "master"
          MASTER_PASSWORD: '{{`{{ .MASTER_PASSWORD | b64enc }}`}}'
          MASTER_ACCESS_TOKEN: '{{`{{ .MASTER_ACCESS_TOKEN | b64enc }}`}}'
          MASTER_DOMAIN: '{{ printf "https://master.%s" .Values.clusterDomainUrl }}'
          ADMIN_USER: "admin"
          ADMIN_PASSWORD: '{{`{{ .ADMIN_PASSWORD | b64enc }}`}}'
          ADMIN_ACCESS_TOKEN: '{{`{{ .ADMIN_ACCESS_TOKEN | b64enc }}`}}'
          TENANT_NAME: "maas"
          ## TODO: Validate if this is equal to the adminURL in the 3scale-maas-tenant-secret
          adminURL: '{{ printf "https://maas-admin.%s" .Values.clusterDomainUrl }}'
          token: '{{`{{ .ADMIN_ACCESS_TOKEN | b64enc }}`}}'
