apiVersion: generators.external-secrets.io/v1alpha1
kind: ClusterGenerator
metadata:
  name: maas-3scale-access-key-generator
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    rhoai-example: maas-3scale
    rhoai-example-component: shared-secrets
spec:
  kind: Password
  generator:
    passwordSpec:
      length: 16
      symbols: 0
      noUpper: false
      
