orchestrator:
  host: "localhost"
  port: 8032
detectors:
  - name: hap
    input: true
    output: true
    detector_params: {}
routes:
  - name: all
    detectors:
      - hap
  - name: hap
    detectors:
      - hap
    fallback_message: "I'm sorry, I cannot help with that."
  - name: passthrough
    detectors:
