apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: guardrails-hf-hap

resources:
  - guardrails-orchestrator.yaml

configMapGenerator:
  - name: guardrails-gateway-config
    files:
      - config.yaml=gateway-config.yaml
  - name: guardrails-orchestrator-config
    files:
      - config.yaml=orchestrator-config.yaml

configurations:
  - cm-name-replacement.yaml
