apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: models-as-a-service
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/redhat-ai-services/ai-accelerator-examples.git
        revision: maas
        directories:
          - path: examples/models-as-a-service/components/*
  template:
    metadata:
      name: '{{ .path.basename }}'
      labels:
        app.kubernetes.io/part-of: models-as-a-service
    spec:
      project: models-as-a-service
      source:
        repoURL: https://github.com/redhat-ai-services/ai-accelerator-examples.git
        targetRevision: maas
        path: '{{ .path.path }}'
        helm:
          releaseName: '{{ .path.basename }}-release'
          parameters:
            - name: wildcardDomain
              value: "WILDCARD_DOMAIN"
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .path.basename | replace "-instance" "" | replace "-operator" "" }}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - SkipDryRunOnMissingResource=true
