apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: maas
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: "GIT_REPO_URL"
        revision: "GIT_BRANCH"
        directories:
          - path: examples/models-as-a-service/components/3scale/operator
          - path: examples/models-as-a-service/components/3scale/instance
          - path: examples/models-as-a-service/components/redhat-sso
  template:
    metadata:
      name: '{{"admachad-"}}{{if contains "3scale/operator" .path}}3scale-operator{{else if contains "3scale/instance" .path}}3scale-instance{{else}}{{.path.basename}}{{end}}'
      labels:
        app.kubernetes.io/part-of: maas
    spec:
      project: maas
      source:
        repoURL: "GIT_REPO_URL"
        targetRevision: "GIT_BRANCH"
        path: '{{.path.path}}'
        helm:
          releaseName: '{{"admachad-"}}{{if contains "3scale/operator" .path.path}}3scale-operator{{else if contains "3scale/instance" .path.path}}3scale-instance{{else}}{{.path.basename}}{{end}}-release'
          parameters:
            - name: wildcardDomain
              value: "WILDCARD_DOMAIN"
            - name: storageClassName
              value: "STORAGE_CLASS"
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{"admachad-"}}{{if contains "3scale/operator" .path.path}}openshift-operators{{else if contains "3scale/instance" .path.path}}maas-3scale{{else if eq .path.basename "redhat-sso"}}maas-redhat-sso{{else}}{{.path.basename}}{{end}}'
