apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-create-bucket
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-delete-policy": "before-hook-creation,hook-succeeded"
    "helm.sh/hook-weight": "6"
spec:
  completions: 1
  template:
    metadata:
      name: {{ .Release.Name }}-create-bucket
    spec:
      restartPolicy: Never
      containers:
      - name: minio-bucket
        image: {{ .Values.mcImage.repository }}:{{ .Values.mcImage.tag }}
        env:
          - name: MC_CONFIG_DIR
            value: /tmp/.mc
          - name: MINIO_URL
            value: {{ .Values.minio.url }}
          - name: MINIO_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.minio.secret.name }}
                key: {{ .Values.minio.secret.accessKey }}
          - name: MINIO_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.minio.secret.name }}
                key: {{ .Values.minio.secret.secretKey }}
          - name: MINIO_BUCKET
            value: {{ .Values.minio.bucket }}
        command:
          - "/bin/sh"
          - "-c"
          - |-
            sleep 30 && \
              echo "Setting up minio alias" && \
              mc alias set minio-3scale "$MINIO_URL" "$MINIO_ACCESS_KEY" "$MINIO_SECRET_KEY" && \
              echo "Creating bucket" && \
              mc mb "minio-3scale/$MINIO_BUCKET" --ignore-existing && \
              echo "Bucket created"
