apiVersion: capabilities.3scale.net/v1beta1
kind: DeveloperAccount
metadata:
  name: developer-account
  namespace: '{{ .Values.namespace }}'
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  orgName: "Example MaaS Organization"
  monthlyBillingEnabled: false
  monthlyChargingEnabled: false
