apiVersion: v1
kind: Secret
metadata:
  name: developer-pwd
  namespace: '{{ $.Values.namespace }}'
  annotations:
    "argocd.argoproj.io/sync-wave": "6"
    "argocd.argoproj.io/sync-options": "SkipDryRunOnMissingResource=true"
type: Opaque
stringData:
  password: '{{ randAlphaNum 16 }}'
---
apiVersion: capabilities.3scale.net/v1beta1
kind: DeveloperAccount
metadata:
  name: developer
  namespace: '{{ $.Values.namespace }}'
  annotations:
    "argocd.argoproj.io/sync-wave": "4"
    "argocd.argoproj.io/sync-options": "SkipDryRunOnMissingResource=true"
spec:
  orgName: developer
---
kind: DeveloperUser
apiVersion: capabilities.3scale.net/v1beta1
metadata:
  name: developer
  namespace: '{{ $.Values.namespace }}'
  annotations:
    "argocd.argoproj.io/sync-wave": "8"
    "argocd.argoproj.io/sync-options": "SkipDryRunOnMissingResource=true"
spec:
  username: developer
  email: developer@domain.com
  role: admin
  passwordCredentialsRef:
    name: developer-pwd
  developerAccountRef:
    name: developer
