{{- range $model := .Values.models }}
---
apiVersion: capabilities.3scale.net/v1beta1
kind: ProxyConfigPromote
metadata:
  name: '{{ $model.name }}'
  namespace: '{{ $.Values.namespace }}'
  annotations:
    "argocd.argoproj.io/sync-wave": "10"
    "argocd.argoproj.io/sync-options": "SkipDryRunOnMissingResource=true"
spec:
  productCRName: '{{ $model.name }}'
  production: true
  deleteCR: false
{{- end }}
