apiVersion: apps.3scale.net/v1alpha1
kind: APIManager
metadata:
  name: apimanager
  namespace: '{{ .Values.namespace }}'
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  wildcardDomain: '{{ .Values.wildcardDomain }}'
  resourceRequirementsEnabled: false
  tenantName: maas
  system:
    fileStorage:
      simpleStorageService:
        configurationSecretRef:
          name: minio-s3-auth
  apicast:
    stagingSpec:
      customPolicies:
        - name: llm-metrics
          version: "0.1"
          secretRef:
            name: llm-metrics
      logLevel: debug
    productionSpec:
      customPolicies:
        - name: llm-metrics
          version: "0.1"
          secretRef:
            name: llm-metrics
      logLevel: debug
