{{- range $model := .Values.models }}
---
apiVersion: capabilities.3scale.net/v1beta1
kind: Product
metadata:
  name: '{{ $model.name }}-product'
  namespace: '{{ $.Values.namespace }}'
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  name: '{{ $model.name }}'
  systemName: '{{ $model.name | replace " " "-" | lower }}'
  description: "API Product for {{ $model.name }} model"
  deployment:
    apicastHosted:
      authentication:
        userkey:
          authUserKey: Authorization
          credentials: headers
  backends:
    - name: '{{ $model.name }}-backend'
      path: "/"
  policies:
    - name: "cors"
      version: "1.0.0"
      enabled: true
      configuration:
        allow_methods:
          - "GET"
          - "POST"
          - "DELETE"
          - "PUT"
          - "PATCH"
          - "HEAD"
          - "OPTIONS"
        allow_credentials: true
        allow_origin: "*"
        allow_headers:
          - "Authorization"
          - "Content-type"
          - "Accept"
    - name: "apicast"
      version: "builtin"
      enabled: true
      configuration: {}
  methods:
    hits:
      - name: 'v1/chat/completions_{{ $model.name | replace " " "-" | lower }}'
        systemName: 'v1_chat_completions_{{ $model.name | replace " " "-" | lower }}'
        description: "Chat completions endpoint for {{ $model.name }}"
  mappingRules:
    - httpMethod: POST
      pattern: "/v1/chat/completions"
      metricMethodRef: 'v1_chat_completions_{{ $model.name | replace " " "-" | lower }}'
      increment: 1
  applicationPlans:
    basic:
      name: "Basic"
      setupFee: "0.00"
      state: published
{{- end }}
