apiVersion: v1
kind: Secret
metadata:
  name: issuer-endpoint-secret
  namespace: '{{ .Values.namespace }}'
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    apimanager.apps.3scale.net/watched-by: apimanager
type: Opaque
data:
  issuerEndpoint: '{{ "https://3scale:myclientsecret@redhat-sso.redhat-sso.svc/auth/realms/maas" | b64enc }}'
