apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: 3scale-client
  namespace: '{{ .Values.namespace | default "redhat-sso" }}'
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  realmSelector:
    matchLabels:
      app: '{{ .Values.keycloak.name | default "redhat-sso" }}'
  client:
    clientId: "3scale"
    name: "3scale"
    description: "Client for 3scale integration"
    protocol: "openid-connect"
    enabled: true
    publicClient: false
    standardFlowEnabled: true
    implicitFlowEnabled: false
    directAccessGrantsEnabled: false
    serviceAccountsEnabled: false
    bearerOnly: false
    consentRequired: false
    redirectUris:
      - "*"
    protocolMappers:
      - name: "email verified"
        protocol: "openid-connect"
        protocolMapper: "oidc-usermodel-property-mapper"
        consentRequired: false
        config:
          userinfo.token.claim: "true"
          user.attribute: "emailVerified"
          id.token.claim: "true"
          access.token.claim: "true"
          claim.name: "email_verified"
          jsonType.label: "boolean"
      - name: "org_type"
        protocol: "openid-connect"
        protocolMapper: "oidc-usermodel-attribute-mapper"
        consentRequired: false
        config:
          user.attribute: "email"
          claim.name: "org_name"
          jsonType.label: "String"
          id.token.claim: "true"
          access.token.claim: "true"
          userinfo.token.claim: "true"
          aggregate.attributes: "false"
