apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-tls-cert
spec:
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-production-ec2
  secretName: keycloak-tls-cert-certmanager
  duration: 2160h
  isCA: false
  renewBefore: 360h
  commonName: 'https://{{ .Values.keycloak.name | default "redhat-sso" }}-{{ .Values.namespace | default "redhat-sso" }}.{{ .Values.wildcardDomain }}'
  dnsNames:
    - 'https://{{ .Values.keycloak.name | default "redhat-sso" }}-{{ .Values.namespace | default "redhat-sso" }}.{{ .Values.wildcardDomain }}'
