apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ include "argocd-appgenerator.fullname" . }}
spec:
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - {{ .Values.repoURL }}
