apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: maas-3scale-external-secrets-read-any-secret
  labels:
    rhoai-example: maas-3scale
    rhoai-example-component: shared-secrets
rules:
- apiGroups: [""]
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - authorization.k8s.io
  resources:
  - selfsubjectrulesreviews
  verbs:
  - create
