{{ if not .Values.apimanager.storageClassName -}}
kind: Secret
apiVersion: v1
metadata:
  name: minio-s3-auth
  namespace: '{{ .Values.namespace }}'
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  labels:
    apimanager.apps.3scale.net/watched-by: apimanager
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: minio
  AWS_SECRET_ACCESS_KEY: minio123
  AWS_BUCKET: 3scale-maas
  AWS_REGION: us-east-1
  AWS_HOSTNAME: minio.minio.svc:9000
  AWS_PROTOCOL: HTTP
  AWS_PATH_STYLE: 'true'
{{- end }}
