--- 
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Namespace }}
    argocd.argoproj.io/managed-by: openshift-gitops
    opendatahub.io/dashboard: "true"
    modelmesh-enabled: "false"
  annotations:
    openshift.io/display-name: "LLM Host"
    argocd.argoproj.io/sync-wave: "-1"
