apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: '{{ .Values.keycloak.name | default "rhbk" }}'
  namespace: '{{ .Values.namespace | default "rhbk" }}'
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  labels:
    app: '{{ .Values.keycloak.name | default "rhbk" }}'
    rhoai-example: maas-3scale
    rhoai-example-component: rhbk-instance
spec:
  instances: 1
  startOptimized: false
  db:
    vendor: postgres
    host: postgres-db
    port: 5432
    database: rhbk
    usernameSecret:
      name: postgres-db
      key: POSTGRESQL_USER
    passwordSecret:
      name: postgres-db
      key: POSTGRESQL_PASSWORD
  ingress:
    enabled: true
    className: openshift-default
  proxy:
    headers: xforwarded
  hostname:
    hostname: 'https://{{ .Values.keycloak.name | default "rhbk" }}-{{ .Values.namespace | default "rhbk" }}.{{ .Values.clusterDomainUrl }}'
    backchannelDynamic: true
    strict: false
  http:
    tlsSecret: keycloak-tls-cert
  additionalOptions:
    - name: http-management-relative-path
      value: /management
